### ISSUE TITLE
h.

### ISSUE THREAD

**Issue by Telesphoreo** [TotalFreedomMC/TF-EssentialsX#1]
### Information

Full output of `/ess version`: h.

Server log (upload `logs/latest.log` to [Gist](https://gist.github.com/)): h

EssentialsX config (upload `plugins/Essentials/config.yml` to [Gist](https://gist.github.com/)): h

### Details

Describe your issue here.

### ### 

> [`_****_`](`

> h

`)

**Comment by lemonsked** [comment]
h.

**Comment by script-head** [comment]
removed issue template
